[workspace]
resolver = "2"
members = [
    "contracts/energy_gateway",
    "daemon",
]

[profile.release]
opt-level = "z"
lto = true
overflow-checks = true
codegen-units = 1
strip = true

[profile.contract]
inherits = "release"
opt-level = "z"
lto = true
overflow-checks = true
codegen-units = 1
strip = true
debug = false


